name: Build and Push

# Run workflow on pushes to main branch or by manual dispatch
on:
  push:
    branches:
      - main
      - develop
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build-publish:
    runs-on: ubuntu-latest
    name: Build and publish modulo image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build . --file ./Dockerfile  --tag modulo
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push latest image
        run: |
          ${{ env.GITHUB_EVENT_NAME }}
          IMAGE_NAME=${{ github.repository }}:latest
          IMAGE_NAME=${IMAGE_NAME/_/-}
          docker tag modulo ghcr.io/${IMAGE_NAME}
          docker push ghcr.io/${IMAGE_NAME}

      - name: Push tagged image
        if: ${{ env.GITHUB_EVENT_NAME == 'release' }}
        run: |
          echo ${{ env.GITHUB_REF }}
          IMAGE_NAME=${{ github.repository }}:${{ env.GITHUB_REF }}
          IMAGE_NAME=${IMAGE_NAME/_/-}
          docker tag modulo ghcr.io/${IMAGE_NAME}
          docker push ghcr.io/${IMAGE_NAME}